name: Build all targets

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_linux:
    name: Build linux ${{ matrix.settings.target }}
    uses: ./.github/workflows/build_linux.yml
    with:
      node_version: ${{ matrix.node-version }}
      target: ${{ matrix.settings.target }}
      build_command: ${{ matrix.settings.build }}
      host: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [20]
        settings:
          - target: x86_64-unknown-linux-gnu
            build: pnpm build --target x86_64-unknown-linux-gnu --use-napi-cross
          - target: x86_64-unknown-linux-musl
            build: pnpm build --target x86_64-unknown-linux-musl -x
          - target: aarch64-unknown-linux-gnu
            build: pnpm build --target aarch64-unknown-linux-gnu --use-napi-cross
          - target: aarch64-unknown-linux-musl
            build: pnpm build --target aarch64-unknown-linux-musl -x
          - target: armv7-unknown-linux-gnueabihf
            build: pnpm build --target armv7-unknown-linux-gnueabihf --use-napi-cross
          - target: aarch64-linux-android
            build: pnpm build --target aarch64-linux-android
          - target: armv7-linux-androideabi
            build: pnpm build --target armv7-linux-androideabi
